### ISSUE TITLE
segfault on Arch64

### ISSUE THREAD

**Issue by t1csi** [kernelhcy/DeaDBeeF-MPRIS-plugin#11]
kernel = 3.5.4-1-ARCH
arch = x86-64
gcc = 4.7.1
deadbeef = 0.5.5
glibc = 2.16.0

gdb output:
GNU gdb (GDB) 7.5
...
This GDB was configured as "x86_64-unknown-linux-gnu".
...
Reading symbols from /usr/bin/deadbeef...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/deadbeef 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
starting deadbeef 0.5.5
server_start
loading plugins from /home/myusername/.local/lib/deadbeef
loading plugins from /usr/lib/deadbeef
plug_load_all: scandir found 165 files
loading plugin /usr/lib/deadbeef/aac.so
loading plugin /usr/lib/deadbeef/adplug.so
loading plugin /usr/lib/deadbeef/alsa.so
loading plugin /usr/lib/deadbeef/artwork.so
loading plugin /usr/lib/deadbeef/cdda.so
loading plugin /usr/lib/deadbeef/converter.so
loading plugin /usr/lib/deadbeef/converter_gtk3.so
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/libgobject-2.0.so.0.3200.4-gdb.py", line 9, in <module>
    from gobject import register
  File "/usr/share/glib-2.0/gdb/gobject.py", line 3, in <module>
    import gdb.backtrace
ImportError: No module named backtrace
loading plugin /usr/lib/deadbeef/dca.so
loading plugin /usr/lib/deadbeef/ddb_ao.so
loading plugin /usr/lib/deadbeef/ddb_dumb.so
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib/deadbeef/ddb_shn.so
loading plugin /usr/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/lib/deadbeef/ffap.so
loading plugin /usr/lib/deadbeef/flac.so
loading plugin /usr/lib/deadbeef/gme.so
loading plugin /usr/lib/deadbeef/hotkeys.so
loading plugin /usr/lib/deadbeef/jack.so
loading plugin /usr/lib/deadbeef/lastfm.so
loading plugin /usr/lib/deadbeef/m3u.so
loading plugin /usr/lib/deadbeef/mms.so
loading plugin /usr/lib/deadbeef/mpgmad.so
loading plugin /usr/lib/deadbeef/mpris.so
MPRIS Debug Info: Load...
loading plugin /usr/lib/deadbeef/musepack.so
loading plugin /usr/lib/deadbeef/notify.so
loading plugin /usr/lib/deadbeef/nullout.so
loading plugin /usr/lib/deadbeef/oss.so
loading plugin /usr/lib/deadbeef/pulse.so
loading plugin /usr/lib/deadbeef/shellexec.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib/deadbeef/sid.so
loading plugin /usr/lib/deadbeef/sndfile.so
loading plugin /usr/lib/deadbeef/supereq.so
loading plugin /usr/lib/deadbeef/tta.so
loading plugin /usr/lib/deadbeef/vfs_curl.so
loading plugin /usr/lib/deadbeef/vfs_zip.so
loading plugin /usr/lib/deadbeef/vorbis.so
loading plugin /usr/lib/deadbeef/vtx.so
loading plugin /usr/lib/deadbeef/wavpack.so
loading plugin /usr/lib/deadbeef/wildmidi.so
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib/deadbeef/ddb_gui_GTK3.so
[New Thread 0x7fffe6cfa700 (LWP 22216)]
[New Thread 0x7fffe64f9700 (LWP 22217)]
[New Thread 0x7fffe5cf8700 (LWP 22218)]
[New Thread 0x7fffe54f7700 (LWP 22219)]
MPRIS Debug Info: MPRIS V1 Starting...
[New Thread 0x7fffe4cf6700 (LWP 22220)]
MPRIS Debug Info: MPRIS V2 Starting...
[New Thread 0x7fffdffff700 (LWP 22221)]
[New Thread 0x7fffdf7fe700 (LWP 22222)]
MPRIS Debug Info: name acquired: org.mpris.deadbeef
MPRIS Debug Info: name acquired: org.mpris.MediaPlayer2.deadbeef
gtkui plugin compiled for gtk version: 3.4.4
[New Thread 0x7fffdeffd700 (LWP 22223)]
[Thread 0x7fffdffff700 (LWP 22221) exited]

(deadbeef:22213): Gdk-WARNING **: deadbeef: Fatal IO error 11 (Erőforrás átmenetileg nem érhető el) on X server :0.

[Thread 0x7fffe5cf8700 (LWP 22218) exited]
[Thread 0x7fffdf7fe700 (LWP 22222) exited]
[Thread 0x7fffe4cf6700 (LWP 22220) exited]
[Thread 0x7fffe54f7700 (LWP 22219) exited]
[Thread 0x7fffe64f9700 (LWP 22217) exited]
[Thread 0x7fffe6cfa700 (LWP 22216) exited]
[Thread 0x7ffff7fca700 (LWP 22213) exited]
[Inferior 1 (process 22213) exited with code 01](gdb) where 
No stack.

---

console log: 
starting deadbeef 0.5.5
server_start
loading plugins from /home/myusername/.local/lib/deadbeef
loading plugins from /usr/lib/deadbeef
plug_load_all: scandir found 165 files
loading plugin /usr/lib/deadbeef/aac.so
loading plugin /usr/lib/deadbeef/adplug.so
loading plugin /usr/lib/deadbeef/alsa.so
loading plugin /usr/lib/deadbeef/artwork.so
loading plugin /usr/lib/deadbeef/cdda.so
loading plugin /usr/lib/deadbeef/converter.so
loading plugin /usr/lib/deadbeef/converter_gtk3.so
loading plugin /usr/lib/deadbeef/dca.so
loading plugin /usr/lib/deadbeef/ddb_ao.so
loading plugin /usr/lib/deadbeef/ddb_dumb.so
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib/deadbeef/ddb_shn.so
loading plugin /usr/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/lib/deadbeef/ffap.so
loading plugin /usr/lib/deadbeef/flac.so
loading plugin /usr/lib/deadbeef/gme.so
loading plugin /usr/lib/deadbeef/hotkeys.so
loading plugin /usr/lib/deadbeef/jack.so
loading plugin /usr/lib/deadbeef/lastfm.so
loading plugin /usr/lib/deadbeef/m3u.so
loading plugin /usr/lib/deadbeef/mms.so
loading plugin /usr/lib/deadbeef/mpgmad.so
loading plugin /usr/lib/deadbeef/mpris.so
MPRIS Debug Info: Load...
loading plugin /usr/lib/deadbeef/musepack.so
loading plugin /usr/lib/deadbeef/notify.so
loading plugin /usr/lib/deadbeef/nullout.so
loading plugin /usr/lib/deadbeef/oss.so
loading plugin /usr/lib/deadbeef/pulse.so
loading plugin /usr/lib/deadbeef/shellexec.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib/deadbeef/sid.so
loading plugin /usr/lib/deadbeef/sndfile.so
loading plugin /usr/lib/deadbeef/supereq.so
loading plugin /usr/lib/deadbeef/tta.so
loading plugin /usr/lib/deadbeef/vfs_curl.so
loading plugin /usr/lib/deadbeef/vfs_zip.so
loading plugin /usr/lib/deadbeef/vorbis.so
loading plugin /usr/lib/deadbeef/vtx.so
loading plugin /usr/lib/deadbeef/wavpack.so
loading plugin /usr/lib/deadbeef/wildmidi.so
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib/deadbeef/ddb_gui_GTK3.so
MPRIS Debug Info: MPRIS V1 Starting...
MPRIS Debug Info: MPRIS V2 Starting...
MPRIS Debug Info: name acquired: org.mpris.deadbeef
MPRIS Debug Info: name acquired: org.mpris.MediaPlayer2.deadbeef
gtkui plugin compiled for gtk version: 3.4.4
Segmentation Fault
backtrace() returned 12 addresses
deadbeef() [0x4037c0]
/usr/lib/libc.so.6(+0x35020) [0x7f6f4cacc020]
/usr/lib/libICE.so.6(+0x101a7) [0x7f6f3c68d1a7]
/usr/lib/libICE.so.6(IceProcessMessages+0x2c7) [0x7f6f3c68e957]
/usr/lib/deadbeef/ddb_gui_GTK3.so(+0x54ad2) [0x7f6f3caf5ad2]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x135) [0x7f6f46d88475]
/usr/lib/libglib-2.0.so.0(+0x477a8) [0x7f6f46d887a8]
/usr/lib/libglib-2.0.so.0(g_main_loop_run+0x72) [0x7f6f46d88ba2]
/usr/lib/deadbeef/mpris.so(+0x1f72) [0x7f6f40ee9f72]
/usr/lib/libglib-2.0.so.0(+0x6a0e5) [0x7f6f46dab0e5]
/usr/lib/libpthread.so.0(+0x7e0f) [0x7f6f4ce45e0f]
/usr/lib/libc.so.6(clone+0x6d) [0x7f6f4cb7d45d]

**Comment by Serranya** [comment]
If you only need MPRISv2 and an dependency on glibc >= 2.32 does not bother you, you can take a look at my version of this Plugin https://github.com/Serranya/deadbeef-mpris2-plugin
